//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace empty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int ProductId { get; set; }
        public string productname { get; set; }
        public string category { get; set; }
        public string logo { get; set; }
        public Nullable<float> price { get; set; }
        public Nullable<int> CID { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
